import { z } from "zod";
import { getEnv } from "./env.js";

export const ResearchResultSchema = z.object({
  decision: z.enum(["qualified", "disqualified", "needs_review"]),
  scores: z.object({ businessFit: z.number().int().min(0).max(10), websiteNeed: z.number().int().min(0).max(10), abilityToPay: z.number().int().min(0).max(10), contactability: z.number().int().min(0).max(10), urgency: z.number().int().min(0).max(10), salesOpportunity: z.number().int().min(0).max(10) }),
  problems: z.array(z.object({ category: z.string().min(1), title: z.string().min(1), evidence: z.string().min(1), businessConsequence: z.string().min(1), recommendedImprovement: z.string().optional().default(""), confidence: z.number().min(0).max(1), outreachValue: z.enum(["low", "medium", "high"]) })).max(8),
  researchSummary: z.string().min(1), primaryOutreachAngle: z.string().nullable(), qualificationReason: z.string().min(1), confidence: z.number().min(0).max(1),
});
export type ResearchResult = z.infer<typeof ResearchResultSchema>;
export type ResearchLead = { businessName: string | null; domain: string; landingPageUrl: string; keyword: string; adSource: string; lighthouseScore: number; lcp: number; cls: number | null; tbt: number | null; email: string | null; phone: string | null; address: string | null; enrichmentNotes: string | null; isAgencyManaged: boolean; agencyName: string | null; isNationalChain: boolean; chainReason: string | null; };
export const RESEARCH_VERSION = "lead-research-v1";
export function calculatePriority(scores: ResearchResult["scores"]): number { return Math.round((scores.businessFit*.20 + scores.websiteNeed*.25 + scores.abilityToPay*.15 + scores.contactability*.15 + scores.urgency*.10 + scores.salesOpportunity*.15)*10); }
function stripHtml(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim().slice(0,18000)}
async function fetchWebsiteText(url:string){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),12000);try{const response=await fetch(url,{signal:controller.signal,headers:{"User-Agent":"LeadMinerResearch/1.0"},redirect:"follow"});if(!response.ok)return `Website fetch failed with HTTP ${response.status}`;return stripHtml(await response.text())}catch(error){return `Website fetch failed: ${error instanceof Error?error.message:String(error)}`}finally{clearTimeout(timeout)}}
function jsonSchema(){return {type:"object",additionalProperties:false,required:["decision","scores","problems","researchSummary","primaryOutreachAngle","qualificationReason","confidence"],properties:{decision:{type:"string",enum:["qualified","disqualified","needs_review"]},scores:{type:"object",additionalProperties:false,required:["businessFit","websiteNeed","abilityToPay","contactability","urgency","salesOpportunity"],properties:Object.fromEntries(["businessFit","websiteNeed","abilityToPay","contactability","urgency","salesOpportunity"].map(k=>[k,{type:"integer",minimum:0,maximum:10}]))},problems:{type:"array",maxItems:8,items:{type:"object",additionalProperties:false,required:["category","title","evidence","businessConsequence","recommendedImprovement","confidence","outreachValue"],properties:{category:{type:"string"},title:{type:"string"},evidence:{type:"string"},businessConsequence:{type:"string"},recommendedImprovement:{type:"string"},confidence:{type:"number",minimum:0,maximum:1},outreachValue:{type:"string",enum:["low","medium","high"]}}}},researchSummary:{type:"string"},primaryOutreachAngle:{type:["string","null"]},qualificationReason:{type:"string"},confidence:{type:"number",minimum:0,maximum:1}}}}
export async function researchLead(lead:ResearchLead, model:string):Promise<{result:ResearchResult;model:string;inputTokens?:number;outputTokens?:number}>{const env=getEnv();if(!env.OPENAI_API_KEY)throw new Error("OPENAI_API_KEY is not configured");const evidence={...lead,websiteText:await fetchWebsiteText(lead.landingPageUrl)};const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model,input:[{role:"system",content:[{type:"input_text",text:"You qualify local-business web-development prospects. Use only supplied evidence. Never invent a website problem. Prefer concrete business-impact problems over generic design opinions. A high-confidence outreach problem must quote or precisely describe evidence present in the packet. Disqualify obvious national chains, agency-managed sites, non-businesses, or prospects with no meaningful opportunity. Scores are 0-10."}]},{role:"user",content:[{type:"input_text",text:`Analyze this Lead Miner evidence packet:\n${JSON.stringify(evidence)}`}]}],text:{format:{type:"json_schema",name:"lead_research",strict:true,schema:jsonSchema()}}})});if(!response.ok)throw new Error(`OpenAI research failed (${response.status}): ${await response.text()}`);const data=await response.json() as any;const raw=data.output_text??data.output?.flatMap((o:any)=>o.content??[]).find((c:any)=>c.type==="output_text")?.text;if(!raw)throw new Error("OpenAI returned no structured research output");return {result:ResearchResultSchema.parse(JSON.parse(raw)),model:data.model??model,inputTokens:data.usage?.input_tokens,outputTokens:data.usage?.output_tokens}}
