import type { Express } from "express";
import type { PrismaClient } from "../generated/prisma/client.js";
import { registerCrmOperationsRoutes } from "./crm-operations-routes.js";

function pct(numerator:number,denominator:number){return denominator>0?Math.round((numerator/denominator)*1000)/10:0;}
function money(value:number){return Math.round(value*100000)/100000;}
function bucketPriority(score:number|null){if(score==null)return"unscored";if(score>=80)return"80-100";if(score>=60)return"60-79";if(score>=40)return"40-59";return"0-39";}
function cohortKey(date:Date|null|undefined){return date?`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,"0")}`:"unknown";}

export function registerAnalyticsRoutes(app:Express,prisma:PrismaClient){
 registerCrmOperationsRoutes(app,prisma);
 app.get("/api/analytics/summary",async(_req,res)=>{try{
  const[leads,sentMessages,jobs]=await Promise.all([
   prisma.lead.findMany({where:{outreachMessages:{some:{status:"sent"}}},select:{id:true,keyword:true,category:true,priorityScore:true,primaryOutreachAngle:true,replyStatus:true,lastReplyAt:true,status:true,outreachMessages:{where:{status:"sent"},select:{kind:true,sequenceNumber:true,angle:true,sentAt:true}},assetAssessments:{orderBy:{createdAt:"desc"},take:1,select:{findings:{select:{category:true,significance:true,confidence:true}}}}}}),
   prisma.outreachMessage.findMany({where:{status:"sent"},select:{leadId:true,kind:true,sequenceNumber:true,sentAt:true}}),
   prisma.aIJob.findMany({select:{leadId:true,type:true,model:true,status:true,inputTokens:true,cachedTokens:true,outputTokens:true,estimatedCost:true,createdAt:true}}),
  ]);
  const replied=leads.filter(l=>Boolean(l.replyStatus||l.lastReplyAt));const interested=leads.filter(l=>["interested","booking_intent"].includes(l.replyStatus??"")||["interested","call_scheduled","proposal_sent","won"].includes(l.status));const meetings=leads.filter(l=>["call_scheduled","proposal_sent","won"].includes(l.status));const wins=leads.filter(l=>l.status==="won");const bounced=leads.filter(l=>l.replyStatus==="bounce"||l.status==="bounced");const unsubscribed=leads.filter(l=>l.replyStatus==="unsubscribe"||l.status==="unsubscribed");const positive=new Set(["interested","booking_intent","question","referral"]);
  const makeBreakdown=(keyFn:(lead:typeof leads[number])=>string)=>{const map=new Map<string,{contacted:number;replied:number;positive:number;meetings:number;won:number}>();for(const lead of leads){const key=keyFn(lead)||"unknown";const row=map.get(key)??{contacted:0,replied:0,positive:0,meetings:0,won:0};row.contacted++;if(lead.replyStatus||lead.lastReplyAt)row.replied++;if(positive.has(lead.replyStatus??"")||["interested","call_scheduled","proposal_sent","won"].includes(lead.status))row.positive++;if(["call_scheduled","proposal_sent","won"].includes(lead.status))row.meetings++;if(lead.status==="won")row.won++;map.set(key,row);}return Array.from(map.entries()).map(([key,row])=>({key,...row,replyRate:pct(row.replied,row.contacted),positiveRate:pct(row.positive,row.contacted),meetingRate:pct(row.meetings,row.contacted),winRate:pct(row.won,row.contacted)})).sort((a,b)=>b.contacted-a.contacted||b.replyRate-a.replyRate);};
  const findingMap=new Map<string,{contacted:number;replied:number;positive:number;meetings:number;won:number}>();for(const lead of leads){const categories=new Set((lead.assetAssessments[0]?.findings??[]).filter(f=>f.significance!=="low"&&f.confidence>=0.6).map(f=>f.category));for(const category of categories){const row=findingMap.get(category)??{contacted:0,replied:0,positive:0,meetings:0,won:0};row.contacted++;if(lead.replyStatus||lead.lastReplyAt)row.replied++;if(positive.has(lead.replyStatus??"")||["interested","call_scheduled","proposal_sent","won"].includes(lead.status))row.positive++;if(["call_scheduled","proposal_sent","won"].includes(lead.status))row.meetings++;if(lead.status==="won")row.won++;findingMap.set(category,row);}}
  const byFinding=Array.from(findingMap.entries()).map(([key,row])=>({key,...row,replyRate:pct(row.replied,row.contacted),positiveRate:pct(row.positive,row.contacted),meetingRate:pct(row.meetings,row.contacted),winRate:pct(row.won,row.contacted)})).sort((a,b)=>b.contacted-a.contacted||b.replyRate-a.replyRate);
  const touchMap=new Map<number,{sent:number;repliesAttributed:number}>();for(const m of sentMessages){const row=touchMap.get(m.sequenceNumber)??{sent:0,repliesAttributed:0};row.sent++;touchMap.set(m.sequenceNumber,row);}for(const lead of leads){const replyAt=lead.lastReplyAt;if(!replyAt)continue;const before=lead.outreachMessages.filter(m=>m.sentAt&&m.sentAt<=replyAt).sort((a,b)=>(b.sentAt?.getTime()??0)-(a.sentAt?.getTime()??0));const touch=before[0];if(touch){const row=touchMap.get(touch.sequenceNumber)??{sent:0,repliesAttributed:0};row.repliesAttributed++;touchMap.set(touch.sequenceNumber,row);}}
  const followupPerformance=Array.from(touchMap.entries()).sort((a,b)=>a[0]-b[0]).map(([sequenceNumber,row])=>({sequenceNumber,label:sequenceNumber===1?"Initial":sequenceNumber===5?"Follow-up 4 · breakup":`Follow-up ${sequenceNumber-1}`,sent:row.sent,repliesAttributed:row.repliesAttributed,attributedReplyRate:pct(row.repliesAttributed,row.sent)}));
  const ai=jobs.reduce((acc,j)=>{acc.calls++;if(j.status==="failed")acc.failed++;acc.inputTokens+=j.inputTokens??0;acc.cachedTokens+=j.cachedTokens??0;acc.outputTokens+=j.outputTokens??0;acc.estimatedCost+=j.estimatedCost??0;return acc;},{calls:0,failed:0,inputTokens:0,cachedTokens:0,outputTokens:0,estimatedCost:0});const analyzedLeadIds=new Set(jobs.filter(j=>j.type==="lead_research"&&j.status==="complete").map(j=>j.leadId));
  const byModelMap=new Map<string,{calls:number;inputTokens:number;cachedTokens:number;outputTokens:number;estimatedCost:number}>();for(const j of jobs){const row=byModelMap.get(j.model)??{calls:0,inputTokens:0,cachedTokens:0,outputTokens:0,estimatedCost:0};row.calls++;row.inputTokens+=j.inputTokens??0;row.cachedTokens+=j.cachedTokens??0;row.outputTokens+=j.outputTokens??0;row.estimatedCost+=j.estimatedCost??0;byModelMap.set(j.model,row);}
  const sentByLead=new Map<number,Date>();for(const m of sentMessages){if(!m.sentAt)continue;const prior=sentByLead.get(m.leadId);if(!prior||m.sentAt<prior)sentByLead.set(m.leadId,m.sentAt);}const cohortMap=new Map<string,{contacted:number;replied:number;meetings:number;won:number}>();for(const lead of leads){const key=cohortKey(sentByLead.get(lead.id));const row=cohortMap.get(key)??{contacted:0,replied:0,meetings:0,won:0};row.contacted++;if(lead.replyStatus||lead.lastReplyAt)row.replied++;if(["call_scheduled","proposal_sent","won"].includes(lead.status))row.meetings++;if(lead.status==="won")row.won++;cohortMap.set(key,row);}const cohorts=Array.from(cohortMap.entries()).map(([key,row])=>({key,...row,replyRate:pct(row.replied,row.contacted),meetingRate:pct(row.meetings,row.contacted),winRate:pct(row.won,row.contacted)})).sort((a,b)=>b.key.localeCompare(a.key));
  res.json({totals:{contactedLeads:leads.length,messagesSent:sentMessages.length,replies:replied.length,interested:interested.length,meetings:meetings.length,wins:wins.length,bounces:bounced.length,unsubscribes:unsubscribed.length,replyRate:pct(replied.length,leads.length),interestedRate:pct(interested.length,leads.length),meetingRate:pct(meetings.length,leads.length),winRate:pct(wins.length,leads.length),bounceRate:pct(bounced.length,leads.length),unsubscribeRate:pct(unsubscribed.length,leads.length)},ai:{...ai,estimatedCost:money(ai.estimatedCost),costPerAnalyzedLead:analyzedLeadIds.size?money(ai.estimatedCost/analyzedLeadIds.size):0,costPerContactedLead:leads.length?money(ai.estimatedCost/leads.length):0,costPerReply:replied.length?money(ai.estimatedCost/replied.length):0,costPerMeeting:meetings.length?money(ai.estimatedCost/meetings.length):0,costPerWin:wins.length?money(ai.estimatedCost/wins.length):0,byModel:Array.from(byModelMap.entries()).map(([model,row])=>({model,...row,estimatedCost:money(row.estimatedCost)}))},byNiche:makeBreakdown(l=>l.category||l.keyword),byKeyword:makeBreakdown(l=>l.keyword),byAngle:makeBreakdown(l=>l.primaryOutreachAngle||l.outreachMessages.find(m=>m.angle)?.angle||"unknown"),byPriority:makeBreakdown(l=>bucketPriority(l.priorityScore)),byFinding,byProblem:byFinding,followupPerformance,cohorts});
 }catch(error){res.status(500).json({error:error instanceof Error?error.message:String(error)});}});
}
