import type { Express } from "express";
import type { PrismaClient } from "../generated/prisma/client.js";
import { z, ZodError } from "zod";
import { getGmailThread } from "./gmail.js";
import { syncLeadGmailPipelineLabelSafely } from "./gmail-pipeline.js";
import { getAppSettings } from "./settings.js";
import { getAiBudgetStatus } from "./ai-budget.js";
import { ensureInitialOutreachDraft, prioritizeLead } from "./outreach-preparation.js";
import { refreshLeadPriorityForDecision } from "./priority-refresh.js";
import { getEnv } from "./env.js";
import { researchQueueWhere } from "./research-queue.js";

const LifecycleSchema=z.enum(["new","enriching","research_pending","researching","research_failed","qualified","disqualified","ready_for_outreach","held","contacted","followup_due","replied","responded","interested","call_scheduled","proposal_sent","won","lost","rejected","bounced","unsubscribed","closed_no_response"]);
const DecisionSchema=z.enum(["rebuild_candidate","no_material_opportunity","needs_review"]);
const OverrideSchema=z.object({status:LifecycleSchema.optional(),qualificationDecision:DecisionSchema.nullable().optional(),qualificationReason:z.string().max(3000).nullable().optional(),revisitAt:z.string().datetime().nullable().optional(),note:z.string().max(2000).optional()}).refine(v=>Object.keys(v).length>0,{message:"At least one override is required"});
const BulkSchema=z.object({ids:z.array(z.number().int().positive()).min(1).max(100),action:z.enum(["qualify","disqualify","hold","reject","prepare_outreach"]),qualificationDecision:DecisionSchema.optional(),reason:z.string().max(1000).optional()});
function bad(res:any,error:ZodError){res.status(400).json({error:"Invalid request",issues:error.issues});}
async function recordPriorityFailure(prisma:PrismaClient,id:number,context:string,error:unknown){const message=error instanceof Error?error.message:String(error);await prisma.activity.create({data:{leadId:id,type:"priority_calculation_failed",summary:`Priority calculation failed after ${context}: ${message}`}}).catch(()=>undefined);}

export function registerCrmOperationsRoutes(app:Express,prisma:PrismaClient){
  app.get("/api/leads/query",async(req,res)=>{
    const q=req.query as Record<string,string|undefined>;
    const page=Math.max(1,Number(q.page)||1);const pageSize=Math.min(100,Math.max(10,Number(q.pageSize)||50));
    const where:any={};
    if(q.status)where.status=q.status;if(q.qualificationDecision)where.qualificationDecision=q.qualificationDecision;if(q.replyStatus)where.replyStatus=q.replyStatus;
    if(["strong","moderate","none","unknown"].includes(q.performanceOpportunity??""))where.performanceOpportunity=q.performanceOpportunity;
    if(["pending","complete","partial","failed"].includes(q.screeningStatus??""))where.screeningStatus=q.screeningStatus;
    if(q.researchState==="researched")where.lastResearchedAt={not:null};
    if(q.researchState==="pending"){where.lastResearchedAt=null;where.aiJobs={none:{type:"lead_research",status:"failed"}};}
    if(q.researchState==="failed"){where.lastResearchedAt=null;where.aiJobs={some:{type:"lead_research",status:"failed"}};}
    if(q.keyword)where.keyword={contains:q.keyword,mode:"insensitive"};
    if(q.location){where.OR=[{city:{contains:q.location,mode:"insensitive"}},{region:{contains:q.location,mode:"insensitive"}},{address:{contains:q.location,mode:"insensitive"}}];}
    if(q.search){const searchOr=[{businessName:{contains:q.search,mode:"insensitive"}},{domain:{contains:q.search,mode:"insensitive"}},{keyword:{contains:q.search,mode:"insensitive"}}];where.OR=where.OR?[{AND:[{OR:where.OR},{OR:searchOr}]}]:searchOr;}
    if(q.hasEmail==="true")where.email={not:null};if(q.hasEmail==="false")where.email=null;if(q.hasPhone==="true")where.phone={not:null};if(q.hasPhone==="false")where.phone=null;
    if(q.agencyManaged==="true")where.isAgencyManaged=true;if(q.agencyManaged==="false")where.isAgencyManaged=false;if(q.chain==="true")where.isNationalChain=true;if(q.chain==="false")where.isNationalChain=false;
    if(q.ads==="true")where.adSource="paid_ad";if(q.minPriority)where.priorityScore={...(where.priorityScore??{}),gte:Number(q.minPriority)};if(q.maxPriority)where.priorityScore={...(where.priorityScore??{}),lte:Number(q.maxPriority)};
    if(q.problemCategory)where.assetAssessments={some:{findings:{some:{category:q.problemCategory}}}};
    if(q.outreachState)where.outreachMessages={some:{status:q.outreachState}};
    const sortMap:any={priorityScore:{priorityScore:{sort:q.sortDir==="asc"?"asc":"desc",nulls:"last"}},lcp:{lcp:q.sortDir==="asc"?"asc":"desc"},createdAt:{createdAt:q.sortDir==="asc"?"asc":"desc"},followUpDate:{followUpDate:{sort:q.sortDir==="asc"?"asc":"desc",nulls:"last"}},lastOutreachDate:{lastOutreachDate:{sort:q.sortDir==="asc"?"asc":"desc",nulls:"last"}},lastReplyAt:{lastReplyAt:{sort:q.sortDir==="asc"?"asc":"desc",nulls:"last"}}};
    const orderBy=sortMap[q.sortBy??"priorityScore"]??sortMap.priorityScore;
    try{const[leads,total]=await Promise.all([prisma.lead.findMany({where,orderBy:[orderBy,{createdAt:"desc"}],skip:(page-1)*pageSize,take:pageSize,include:{assetAssessments:{orderBy:{createdAt:"desc"},take:1,include:{findings:{take:3,orderBy:{confidence:"desc"}}}},outreachMessages:{where:{status:{in:["draft","approved","sending","sent"]}},orderBy:{sequenceNumber:"desc"},take:1},aiJobs:{where:{type:"lead_research",status:"failed"},orderBy:{createdAt:"desc"},take:1,select:{status:true}}}}),prisma.lead.count({where})]);res.json({leads,total,page,pageSize,totalPages:Math.max(1,Math.ceil(total/pageSize))});}catch(error){res.status(500).json({error:error instanceof Error?error.message:String(error)});}
  });

  app.patch("/api/leads/:id/override",async(req,res)=>{const id=Number(req.params["id"]);if(!Number.isInteger(id)){res.status(400).json({error:"Invalid lead id"});return;}let parsed:z.infer<typeof OverrideSchema>;try{parsed=OverrideSchema.parse(req.body);}catch(error){if(error instanceof ZodError){bad(res,error);return;}throw error;}try{const lead=await prisma.$transaction(async tx=>{const data:any={};if(parsed.status!==undefined)data.status=parsed.status;if(parsed.qualificationDecision!==undefined){data.qualificationDecision=parsed.qualificationDecision;data.priorityScore=null;data.priorityBreakdown={};}if(parsed.qualificationReason!==undefined)data.qualificationReason=parsed.qualificationReason;if(parsed.revisitAt!==undefined)data.revisitAt=parsed.revisitAt?new Date(parsed.revisitAt):null;if(parsed.status&&["held","replied","interested","call_scheduled","proposal_sent","won","lost","rejected","bounced","unsubscribed","closed_no_response"].includes(parsed.status))data.followUpDate=null;const updated=await tx.lead.update({where:{id},data});await tx.activity.create({data:{leadId:id,type:"manual_override",summary:`Operator override${parsed.status?`: ${parsed.status}`:""}`,metadata:{...parsed}}});if(parsed.note)await tx.activity.create({data:{leadId:id,type:"manual_note",summary:parsed.note}});return updated;});let priorityScore=lead.priorityScore;if(parsed.qualificationDecision!==undefined){try{priorityScore=await refreshLeadPriorityForDecision(prisma,id,parsed.qualificationDecision);}catch(error){await recordPriorityFailure(prisma,id,"operator override",error);}}await syncLeadGmailPipelineLabelSafely(prisma,id,"operator override");res.json({...lead,priorityScore});}catch(error){res.status(500).json({error:error instanceof Error?error.message:String(error)});}});

  app.post("/api/leads/bulk-action",async(req,res)=>{let parsed:z.infer<typeof BulkSchema>;try{parsed=BulkSchema.parse(req.body);}catch(error){if(error instanceof ZodError){bad(res,error);return;}throw error;}const results:Array<any>=[];for(const id of parsed.ids){try{if(parsed.action==="prepare_outreach"){const priority=await prioritizeLead(prisma,id);const draft=await ensureInitialOutreachDraft(prisma,id);if(!["draft","approved"].includes(draft.status)){const reason=draft.status==="sent"?"Initial outreach has already been sent; follow-up automation owns the next touch":draft.status==="sending"?"Initial outreach is already being sent":"Outreach preparation did not produce an unsent draft";results.push({id,success:false,priorityScore:priority.score,draftId:draft.id,draftStatus:draft.status,error:reason});continue;}results.push({id,success:true,priorityScore:priority.score,draftId:draft.id,draftStatus:draft.status});continue;}const data:any={};if(parsed.action==="qualify"){if(parsed.qualificationDecision!=="rebuild_candidate")throw new Error("Bulk qualify requires rebuild_candidate because outreach is only for custom rebuild opportunities");data.status="qualified";data.qualificationDecision="rebuild_candidate";data.priorityScore=null;data.priorityBreakdown={};}if(parsed.action==="disqualify"){data.status="disqualified";data.qualificationDecision=parsed.qualificationDecision??"no_material_opportunity";data.priorityScore=null;data.priorityBreakdown={};}if(parsed.action==="hold"){data.status="held";data.followUpDate=null;}if(parsed.action==="reject"){data.status="rejected";data.followUpDate=null;}await prisma.$transaction(async tx=>{await tx.lead.update({where:{id},data});await tx.activity.create({data:{leadId:id,type:"bulk_action",summary:`Bulk action: ${parsed.action}${parsed.reason?` — ${parsed.reason}`:""}`,metadata:{action:parsed.action,reason:parsed.reason??null}}});});let priorityScore:number|null=null;if(parsed.action==="qualify"){try{priorityScore=await refreshLeadPriorityForDecision(prisma,id,"rebuild_candidate");}catch(error){await recordPriorityFailure(prisma,id,"bulk qualification",error);}}await syncLeadGmailPipelineLabelSafely(prisma,id,`bulk action ${parsed.action}`);results.push({id,success:true,priorityScore});}catch(error){results.push({id,success:false,error:error instanceof Error?error.message:String(error)});}}res.json({processed:results.length,succeeded:results.filter(r=>r.success).length,failed:results.filter(r=>!r.success).length,results});});

  app.get("/api/leads/:id/thread",async(req,res)=>{const id=Number(req.params["id"]);if(!Number.isInteger(id)){res.status(400).json({error:"Invalid lead id"});return;}try{const lead=await prisma.lead.findUnique({where:{id},include:{emailThreads:{orderBy:{updatedAt:"desc"},take:1},outreachMessages:{where:{status:"sent"},orderBy:{sequenceNumber:"asc"}}}});if(!lead){res.status(404).json({error:"Lead not found"});return;}const threadId=lead.emailThreads[0]?.providerThreadId??lead.outreachMessages.at(-1)?.providerThreadId;if(!threadId){res.json({threadId:null,messages:[]});return;}const messages=await getGmailThread(threadId);res.json({threadId,messages});}catch(error){res.status(500).json({error:error instanceof Error?error.message:String(error)});}});

  app.get("/api/dashboard/operations",async(_req,res)=>{try{const settings=await getAppSettings(prisma);const now=new Date();const start=new Date(now);start.setHours(0,0,0,0);const[researchQueue,qualified,readyToSend,followupsDue,followupsOverdue,replies,interested,meetings,wins,failedJobs,lastRun,aiBudget]=await Promise.all([prisma.lead.count({where:researchQueueWhere() as any}),prisma.lead.count({where:{status:"qualified"}}),prisma.outreachMessage.count({where:{status:"approved",OR:[{scheduledAt:null},{scheduledAt:{lte:now}}]}}),prisma.lead.count({where:{status:"contacted",followUpDate:{lte:now}}}),prisma.lead.count({where:{status:"contacted",followUpDate:{lt:start}}}),prisma.lead.count({where:{replyHandledAt:null,replyStatus:{not:null}}}),prisma.lead.count({where:{status:"interested"}}),prisma.lead.count({where:{status:{in:["call_scheduled","proposal_sent","won"]}}}),prisma.lead.count({where:{status:"won"}}),prisma.aIJob.count({where:{status:"failed"}}),prisma.automationRun.findFirst({orderBy:{startedAt:"desc"}}),getAiBudgetStatus(prisma,settings)]);res.json({researchQueue,qualified,readyToSend,followupsDue,followupsOverdue,replies,interested,meetings,wins,failedJobs,lastRun,aiBudget});}catch(error){res.status(500).json({error:error instanceof Error?error.message:String(error)});}});

  app.get("/api/automation/errors",async(_req,res)=>{try{const[aiJobs,runs,messages]=await Promise.all([prisma.aIJob.findMany({where:{status:"failed"},orderBy:{createdAt:"desc"},take:100,include:{lead:{select:{id:true,businessName:true,domain:true}}}}),prisma.automationRun.findMany({where:{status:{in:["failed","completed_with_errors"]}},orderBy:{startedAt:"desc"},take:100}),prisma.outreachMessage.findMany({where:{sendError:{not:null}},orderBy:{sendAttemptedAt:"desc"},take:100,include:{lead:{select:{id:true,businessName:true,domain:true}}}})]);res.json({aiJobs,runs,messages,total:aiJobs.length+runs.length+messages.length});}catch(error){res.status(500).json({error:error instanceof Error?error.message:String(error)});}});

  app.get("/health/ready",async(_req,res)=>{try{await prisma.$queryRawUnsafe("SELECT 1");const env=getEnv();const readiness={database:true,openai:Boolean(env.OPENAI_API_KEY),gmail:Boolean(env.GMAIL_CLIENT_ID&&env.GMAIL_CLIENT_SECRET&&env.GMAIL_REFRESH_TOKEN),serper:Boolean(env.SERPER_API_KEY),pagespeed:Boolean(env.PAGESPEED_API_KEY)};const ready=Object.values(readiness).every(Boolean);res.status(ready?200:503).json({status:ready?"ready":"degraded",readiness});}catch(error){res.status(503).json({status:"not_ready",readiness:{database:false},error:error instanceof Error?error.message:String(error)});}});
}
