export const DEFAULT_KEYWORDS: string[] = [
  // Granbury / Hood County area
  "plumber granbury tx",
  "electrician granbury tx",
  "pest control granbury tx",
  "roofing contractor granbury tx",
  "hvac granbury tx",
  "landscaping granbury tx",
  "fence company granbury tx",
  "concrete contractor granbury tx",

  // Near Granbury
  "plumber weatherford tx",
  "electrician weatherford tx",
  "pest control weatherford tx",
  "roofing contractor weatherford tx",
  "hvac weatherford tx",
  "plumber cleburne tx",
  "electrician cleburne tx",
  "roofing contractor cleburne tx",
  "plumber stephenville tx",
  "electrician stephenville tx",
  "hvac stephenville tx",
  "plumber mineral wells tx",
  "pest control mineral wells tx",
  "plumber glen rose tx",
  "roofing contractor glen rose tx",

  // DFW suburbs
  "plumber azle tx",
  "electrician azle tx",
  "plumber burleson tx",
  "electrician burleson tx",
  "hvac burleson tx",
  "roofing contractor burleson tx",
  "plumber midlothian tx",
  "electrician midlothian tx",
  "pest control midlothian tx",
  "plumber waxahachie tx",
  "electrician waxahachie tx",
  "roofing contractor waxahachie tx",
  "hvac waxahachie tx",
  "plumber corsicana tx",
  "electrician corsicana tx",
  "plumber hillsboro tx",
  "plumber ennis tx",
  "electrician ennis tx",
  "plumber mansfield tx",
  "electrician mansfield tx",
  "pest control mansfield tx",
  "plumber cedar hill tx",
  "electrician cedar hill tx",
  "plumber crowley tx",
  "plumber aledo tx",
  "roofing contractor aledo tx",

  // Mid-size Texas cities
  "plumber tyler tx",
  "electrician tyler tx",
  "pest control tyler tx",
  "roofing contractor tyler tx",
  "hvac tyler tx",
  "plumber longview tx",
  "electrician longview tx",
  "pest control longview tx",
  "plumber lufkin tx",
  "electrician lufkin tx",
  "plumber nacogdoches tx",
  "electrician nacogdoches tx",
  "plumber wichita falls tx",
  "electrician wichita falls tx",
  "roofing contractor wichita falls tx",
  "hvac wichita falls tx",
  "plumber abilene tx",
  "electrician abilene tx",
  "pest control abilene tx",
  "roofing contractor abilene tx",
  "plumber san angelo tx",
  "electrician san angelo tx",
  "plumber brownwood tx",
  "electrician brownwood tx",
  "plumber temple tx",
  "electrician temple tx",
  "hvac temple tx",
  "plumber killeen tx",
  "electrician killeen tx",
  "roofing contractor killeen tx",

  // Additional service types in key areas
  "garage door repair granbury tx",
  "tree service weatherford tx",
  "painting contractor waxahachie tx",
  "foundation repair burleson tx",
  "septic service stephenville tx",
  "well pump service mineral wells tx",
  "auto body shop cleburne tx",
  "veterinarian granbury tx",
  "dentist granbury tx",
  "dentist weatherford tx",
  "dentist cleburne tx",
];