export const DEFAULT_KEYWORDS: string[] = [
  // Home Services
  "plumber dallas",
  "plumber houston",
  "plumber san antonio",
  "plumber austin",
  "hvac fort worth",
  "hvac houston",
  "hvac san antonio",
  "hvac austin",
  "roofing contractor dallas",
  "roofing contractor houston",
  "electrician fort worth",
  "electrician austin",
  "pest control dallas",
  "pest control houston",

  // Medical / Dental
  "dentist dallas",
  "dentist houston",
  "dentist san antonio",
  "dentist austin",
  "chiropractor fort worth",
  "chiropractor houston",
  "med spa dallas",
  "med spa austin",
  "veterinarian dallas",
  "veterinarian houston",
  "dermatologist san antonio",
  "dermatologist fort worth",

  // Legal
  "personal injury lawyer dallas",
  "personal injury lawyer houston",
  "personal injury lawyer san antonio",
  "family law attorney fort worth",
  "family law attorney austin",
  "dui lawyer dallas",
  "dui lawyer houston",
  "criminal defense lawyer austin",
  "estate planning attorney dallas",
  "estate planning attorney san antonio",

  // Auto Services
  "auto body shop dallas",
  "auto body shop houston",
  "auto detailing fort worth",
  "auto detailing austin",
  "mechanic san antonio",
  "mechanic houston",
  "window tint dallas",
  "car wrap houston",
];
